# -*- coding: utf-8 -*-
"""Counting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aKnsnz-SbEHBdTm4Kr9I1vp6VrC7dLaA
"""

scores = input().split()
count = 0

for i in scores:
  if int(i) < 60:
    count += 1

print(count)